/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ClearCookies: typeof import('./src/components/ClearCookies.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DateNotesDialog: typeof import('./src/components/DateNotesDialog.vue')['default']
    ErrorDialog: typeof import('./src/components/ErrorDialog.vue')['default']
    ForgotPasswordDialog: typeof import('./src/components/ForgotPasswordDialog.vue')['default']
    GlobalDialogs: typeof import('./src/components/GlobalDialogs.vue')['default']
    GlobalNotification: typeof import('./src/components/GlobalNotification.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    NotificationDialog: typeof import('./src/components/NotificationDialog.vue')['default']
    PromptDialog: typeof import('./src/components/PromptDialog.vue')['default']
    PushPermissionPrompt: typeof import('./src/components/PushPermissionPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessDialog: typeof import('./src/components/SuccessDialog.vue')['default']
  }
}
