/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/active-units': RouteRecordInfo<'/active-units', '/active-units', Record<never, never>, Record<never, never>>,
    '/add-agency': RouteRecordInfo<'/add-agency', '/add-agency', Record<never, never>, Record<never, never>>,
    '/add-flagged-unit': RouteRecordInfo<'/add-flagged-unit', '/add-flagged-unit', Record<never, never>, Record<never, never>>,
    '/add-inspection': RouteRecordInfo<'/add-inspection', '/add-inspection', Record<never, never>, Record<never, never>>,
    '/add-maintenance': RouteRecordInfo<'/add-maintenance', '/add-maintenance', Record<never, never>, Record<never, never>>,
    '/add-notice': RouteRecordInfo<'/add-notice', '/add-notice', Record<never, never>, Record<never, never>>,
    '/add-unit': RouteRecordInfo<'/add-unit', '/add-unit', Record<never, never>, Record<never, never>>,
    '/add-user': RouteRecordInfo<'/add-user', '/add-user', Record<never, never>, Record<never, never>>,
    '/add-vacancy': RouteRecordInfo<'/add-vacancy', '/add-vacancy', Record<never, never>, Record<never, never>>,
    '/agency': RouteRecordInfo<'/agency', '/agency', Record<never, never>, Record<never, never>>,
    '/audit-trail': RouteRecordInfo<'/audit-trail', '/audit-trail', Record<never, never>, Record<never, never>>,
    '/dashbaaord': RouteRecordInfo<'/dashbaaord', '/dashbaaord', Record<never, never>, Record<never, never>>,
    '/documents': RouteRecordInfo<'/documents', '/documents', Record<never, never>, Record<never, never>>,
    '/edit-flagged-unit-[id]': RouteRecordInfo<'/edit-flagged-unit-[id]', '/edit-flagged-unit-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/edit-inspection-[id]': RouteRecordInfo<'/edit-inspection-[id]', '/edit-inspection-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/edit-maintenance-[id]': RouteRecordInfo<'/edit-maintenance-[id]', '/edit-maintenance-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/edit-notice-[id]': RouteRecordInfo<'/edit-notice-[id]', '/edit-notice-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/edit-property-[id]': RouteRecordInfo<'/edit-property-[id]', '/edit-property-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/edit-user-[id]': RouteRecordInfo<'/edit-user-[id]', '/edit-user-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/edit-vacancy-[id]': RouteRecordInfo<'/edit-vacancy-[id]', '/edit-vacancy-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/flagged-units': RouteRecordInfo<'/flagged-units', '/flagged-units', Record<never, never>, Record<never, never>>,
    '/inspections': RouteRecordInfo<'/inspections', '/inspections', Record<never, never>, Record<never, never>>,
    '/maintenance': RouteRecordInfo<'/maintenance', '/maintenance', Record<never, never>, Record<never, never>>,
    '/notices': RouteRecordInfo<'/notices', '/notices', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/user-management': RouteRecordInfo<'/user-management', '/user-management', Record<never, never>, Record<never, never>>,
    '/vacancies': RouteRecordInfo<'/vacancies', '/vacancies', Record<never, never>, Record<never, never>>,
    '/view-agency': RouteRecordInfo<'/view-agency', '/view-agency', Record<never, never>, Record<never, never>>,
    '/view-agency-[id]': RouteRecordInfo<'/view-agency-[id]', '/view-agency-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view-flagged-unit-[id]': RouteRecordInfo<'/view-flagged-unit-[id]', '/view-flagged-unit-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view-flagged-units': RouteRecordInfo<'/view-flagged-units', '/view-flagged-units', Record<never, never>, Record<never, never>>,
    '/view-inspection-[id]': RouteRecordInfo<'/view-inspection-[id]', '/view-inspection-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view-maintenance': RouteRecordInfo<'/view-maintenance', '/view-maintenance', Record<never, never>, Record<never, never>>,
    '/view-maintenance-[id]': RouteRecordInfo<'/view-maintenance-[id]', '/view-maintenance-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view-notice': RouteRecordInfo<'/view-notice', '/view-notice', Record<never, never>, Record<never, never>>,
    '/view-notice-[id]': RouteRecordInfo<'/view-notice-[id]', '/view-notice-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view-property': RouteRecordInfo<'/view-property', '/view-property', Record<never, never>, Record<never, never>>,
    '/view-property-[id]': RouteRecordInfo<'/view-property-[id]', '/view-property-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view-user': RouteRecordInfo<'/view-user', '/view-user', Record<never, never>, Record<never, never>>,
    '/view-user-[id]': RouteRecordInfo<'/view-user-[id]', '/view-user-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/view-vacancy-[id]': RouteRecordInfo<'/view-vacancy-[id]', '/view-vacancy-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
